# Generated by Django 5.0.6 on 2024-06-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCommentForm',
            new_name='Comment',
        ),
    ]
