# Generated by Django 5.0.6 on 2024-06-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_remove_comment_firstname_remove_comment_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='firstname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
