# Generated by Django 5.0.6 on 2024-05-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('speed', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('zero_to_hundred', models.CharField(max_length=50)),
                ('combined_fuel_consumption', models.CharField(max_length=50)),
                ('body_class', models.CharField(max_length=50)),
                ('engine_volume', models.CharField(max_length=50)),
                ('engine_power', models.CharField(max_length=50)),
                ('number_of_cylinders', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='images/cars')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
