# Generated by Django 5.0.6 on 2024-06-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_driver_car_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='slug',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='representation',
            name='slug',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
